### ISSUE TITLE
Installing Squander Fails because TBB could not be found

### ISSUE THREAD

**Issue by positr0nium** [rakytap/sequential-quantum-gate-decomposer#96]
I installed tbb and the other C++/Python dependencies, however my build fails (when using `pip install squander`) with the following log:

```
  × Building wheel for squander (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      Not searching for unused variables given on the command line.

      -- The C compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (4.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          /tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPYTHON_LIBRARY:PATH=/home/raphael/miniconda3/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPython_ROOT_DIR:PATH=/home/raphael/miniconda3 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPython3_ROOT_DIR:PATH=/home/raphael/miniconda3 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 10.2.1
      -- The CXX compiler identification is GNU 10.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- The project is built using scikit-build
      CMake Warning (dev) at CMakeLists.txt:40 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: /home/raphael/miniconda3/bin/python (found version "3.11.5")
      CMake Warning (dev) at CMakeLists.txt:41 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonLibs: /home/raphael/miniconda3/lib/libpython3.11.so (found version "3.11.5")
      -- Found NumPy: /tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/numpy/core/include (found version "1.26.4")
      CMake Warning (dev) at CMakeLists.txt:46 (exec_program):
        Policy CMP0153 is not set: The exec_program command should not be called.
        Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        Use execute_process() instead.
      This warning is for project developers.  Use -Wno-dev to suppress it.

      Python syspaths: /home/raphael/miniconda3/lib/python3.11/site-packages/../..
      CMake Warning (dev) at CMakeLists.txt:61 (exec_program):
        Policy CMP0153 is not set: The exec_program command should not be called.
        Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        Use execute_process() instead.
      This warning is for project developers.  Use -Wno-dev to suppress it.

      Include paths: /home/raphael/miniconda3/lib/python3.11/site-packages/../../../include
      CMake Warning (dev) at CMakeLists.txt:88 (exec_program):
        Policy CMP0153 is not set: The exec_program command should not be called.
        Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        Use execute_process() instead.
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at /tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        CMakeLists.txt:99 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at /tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:252 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        CMakeLists.txt:99 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Looking for sgemm_
      -- Looking for sgemm_ - not found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Looking for sgemm_
      -- Looking for sgemm_ - found
      -- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so
      -- Looking for cheev_
      -- Looking for cheev_ - found
      -- Found LAPACK: /usr/lib/x86_64-linux-gnu/libopenblas.so;-lpthread;-lm;-ldl
      -- Looking for MKL_Set_Num_Threads
      -- Looking for MKL_Set_Num_Threads - not found
      -- Looking for openblas_set_num_threads
      -- Looking for openblas_set_num_threads - found
      -- Looking for LAPACKE_zggev
      -- Looking for LAPACKE_zggev - not found
      -- Performing Test HAVE_AVX_EXTENSIONS
      -- Performing Test HAVE_AVX_EXTENSIONS - Success
      -- Performing Test HAVE_AVX2_EXTENSIONS
      -- Performing Test HAVE_AVX2_EXTENSIONS - Success
      -- Using GNU compiler
      CMake Error at CMakeLists.txt:259 (find_library):
        Could not find TBB_LIB using the following names: tbb


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPYTHON_LIBRARY:PATH=/home/raphael/miniconda3/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPython_ROOT_DIR:PATH=/home/raphael/miniconda3 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/raphael/miniconda3/bin/python -DPython3_ROOT_DIR:PATH=/home/raphael/miniconda3 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/raphael/miniconda3/include/python3.11 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-t30g7jo7/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20
        Working directory:
          /tmp/pip-install-qpyz1ehy/squander_3efd226017e54485853abd2fdc212e20/_skbuild/linux-x86_64-3.11/cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for squander
Failed to build squander
ERROR: Could not build wheels for squander, which is required to install pyproject.toml-based projects
```

**Comment by rakytap** [comment]
Dear [positr0nium](https://github.com/positr0nium), can you describe me the way you have installed the TBB library? Do you have installed it system-wide or/and within your python environment via the package tbb-devel?

**Comment by positr0nium** [comment]
Hi @rakytap , I am using WSL. I tried tbb via `pip install tbb` and also via `sudo apt install libtbb-devD`

**Comment by rakytap** [comment]
I see. Please issue pip install tbb-devel  which will provide a more recent version of TBB than libtbb-dev. Actually they might conflict with each other, so I suggest to uninstall libtbb-dev via apt.

if libtbb-dev is used (advanced setup), I suggest to define the environment variables 

$ export TBB_LIB_DIR=path/to/TBB/lib(64)

$ export TBB_INC_DIR=path/to/TBB/include

prior to pip install squander. 

I suggest you to precisely follow the steps under section "Install SQUANDER from Python Package Index (PyPI)" in README.md or the steps detailed in "Developer build" that can be used to have editable installation of squander.

**Comment by positr0nium** [comment]
I am not sure how to identify these paths - please give me the name of some files I would expect within these folders?

**Comment by rakytap** [comment]
Excellent! Glad to hear that!
